### ISSUE TITLE
Add ESLint 9 support

### ISSUE THREAD

**Issue by ai** [thefrontside/javascript#57]
Right now we have this error:

```
npx eslint .

Oops! Something went wrong! :(

ESLint: 9.0.0

TypeError: context.getScope is not a function
Occurred while linting /home/ai/Dev/logux-eslint-config/demo/test.js:5
Rule: "prefer-let/prefer-let"
    at isGlobalScope (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint-plugin-prefer-let@3.0.1/node_modules/eslint-plugin-prefer-let/lib/rules/prefer-let.js:32:22)
    at isTopLevelScope (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint-plugin-prefer-let@3.0.1/node_modules/eslint-plugin-prefer-let/lib/rules/prefer-let.js:44:14)
    at VariableDeclaration (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint-plugin-prefer-let@3.0.1/node_modules/eslint-plugin-prefer-let/lib/rules/prefer-let.js:58:44)
    at ruleErrorHandler (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/linter.js:1145:48)
    at /home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
```

**Comment by azat-io** [comment]
@cowboyd @wKich
Hello! The problem has been fixed. Can you publish a new release of eslint-plugin-prefer-let on npm?

**Comment by azat-io** [comment]
Ping ^
Please, publish new release
